#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Ryuichi Ueda 　　　　　
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
numbers = []                    #入力した数値のリスト
for line in sys.stdin:
    line = line.rstrip()
    num = tonum(line)
    numbers.append(str(num))    #numを文字列に変換してリスト末尾に追加
    ans += num

siki = '+'.join(numbers) #リストの要素に区切り文字で+を追加
print(siki, end = '')
print('=', end='')
print(ans)