#!/usr/bin/python3
# © 2022 Kohei Kato
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)
           　　 
ans = 0   #もともと0.0だったのを0に変更
for line in sys.stdin:
    ans += tonum(line)
           　 
print(ans)
