#!/usr/bin/python3
# SPDX-FileCopyrightText: Kohei Kato　　　　　
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
numbers = []                    #入力した数値のリスト
for line in sys.stdin:
    line = line.rstrip()
    if not line:
        #空行が入力されたら総和を表示
        siki = '+'.join(numbers)
        print(siki, end='')
        print("=", end='')
        print(ans)
        exit()  #終了
    else:
        num = tonum(line)
        numbers.append(str(num))    #読み取ったnumを文字列に変換してリスト末尾に追加
        ans += num

siki = '+'.join(numbers) #リストの要素に区切り文字で+を追加
print(siki, end = '')
print('=', end='')
print(ans)